version: "3"
services:
  gocd-server:
    image: "gocd/gocd-server:${GOCD_VERSION}"
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - "./godata:/godata"
      - "./home-go:/home/go"
    environment:
      - GO_SERVER_SYSTEM_PROPERTIES="-Dfoo=bar"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  
  gocd-agent:
    image: "${GOCD_AGENT_IMAGE}:${GOCD_VERSION}"
    links:
      - gocd-server
    environment:
      - GO_SERVER_URL="https://gocd-server:8154/go"

