version: "2.1"
services:
  gocd-server:
    image: "gocd/gocd-server:${GOCD_VERSION}"
    ports:
      - "${GO_SERVER_HTTP_PORT}:8153"
      - "${GO_SERVER_HTTPS_PORT}:8154"
    volumes:
      - "${SERVER_GO_DATA_PATH}:/godata"
      - "${SERVER_HOME_GO_PATH}:/home/go"
    environment:
      - GO_SERVER_SYSTEM_PROPERTIES="${GO_SERVER_SYSTEM_PROPERTIES}"

  # centos-6-gocd-agent:
  #   image: "gocd/gocd-agent-centos-6:${GOCD_VERSION}"
  #   links:
  #     - gocd-server
  #   extends:
  #     file: base.agent.yml
  #     service: gocd-agent
  #
  # centos-7-gocd-agent:
  #   image: "gocd/gocd-agent-centos-7:${GOCD_VERSION}"
  #   links:
  #     - gocd-server
  #   extends:
  #     file: base.agent.yml
  #     service: gocd-agent
  #   environment:
  #
  #
  # debian-8-gocd-agent:
  #   image: "gocd/gocd-agent-debian-8:${GOCD_VERSION}"
  #   links:
  #     - gocd-server
  #   extends:
  #     file: base.agent.yml
  #     service: gocd-agent
