version: "2.1"
services:
  build_agent:
    image: "${GOCD_AGENT_IMAGE_REPOSITORY}:${GOCD_VERSION}"
    links:
      - gocd-server
    environment:
      - GO_SERVER_URL="https://gocd-server:${GO_SERVER_HTTPS_PORT}/go"
    env_file:
      - .env
      - env/build.agent.env
